import { getCookie } from "@/actions/cookies"
import { AppLayout } from "@/components/app-layout"
import { UserProvider } from "@/contexts/user-provider"
import type { Metadata } from "next"
import { redirect } from "next/navigation"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const token = await getCookie("token")

  if (!token) {
    redirect("/login")
  }

  return (
    <UserProvider token={token}>
      <AppLayout>{children}</AppLayout>
    </UserProvider>
  )
}
